"""
Client Logging Module
Forwards all client logs to the server for centralised storage.

Logs are sent via HTTP POST to the server's /api/logs endpoint.
A console handler is kept locally for real-time visibility.
"""

import logging
import platform
import threading
import time
import uuid

import requests

from config import (
    API_BASE_URL,
    API_KEY,
    MAX_RETRIES,
    REQUEST_TIMEOUT_SECONDS,
    RETRY_BACKOFF_FACTOR,
    USER_ID,
)

logger = logging.getLogger(__name__)

# Unique client identifier: prefer configured USER_ID, fallback to machine info
CLIENT_ID = USER_ID or f"{platform.node()}-{uuid.getnode()}"

# Number of retry attempts for sending logs to the server
LOG_SEND_RETRIES = max(MAX_RETRIES, 3)


def send_log_to_server(level: str, message: str) -> bool:
    """
    Send a log entry to the server via HTTP POST to /api/logs.

    Implements retry with exponential backoff. If the server is unreachable,
    the function returns False and the log remains only in the local file.

    Args:
        level: Log level string (e.g. "INFO", "WARNING", "ERROR").
        message: The log message text.

    Returns:
        True if the log was successfully delivered, False otherwise.
    """
    url = f"{API_BASE_URL.rstrip('/')}/api/logs"
    payload = {
        "level": level,
        "message": message,
        "client_id": CLIENT_ID,
    }
    headers = {
        "Content-Type": "application/json",
        "X-API-Key": API_KEY,
        "X-User-Id": USER_ID,
    }

    for attempt in range(1, LOG_SEND_RETRIES + 1):
        try:
            response = requests.post(
                url,
                json=payload,
                headers=headers,
                timeout=REQUEST_TIMEOUT_SECONDS,
            )
            if response.status_code == 200:
                return True

            # Non-retryable auth errors
            if response.status_code in (401, 403):
                logger.debug("Log send rejected by server (auth error)")
                return False

            logger.debug(
                "Log send attempt %d/%d: server returned %d",
                attempt, LOG_SEND_RETRIES, response.status_code,
            )

        except requests.exceptions.RequestException:
            logger.debug(
                "Log send attempt %d/%d: connection failed",
                attempt, LOG_SEND_RETRIES,
            )

        # Exponential backoff before next retry
        if attempt < LOG_SEND_RETRIES:
            time.sleep(RETRY_BACKOFF_FACTOR ** attempt)

    return False


class ServerLogHandler(logging.Handler):
    """
    Custom logging handler that sends all log records to the server.

    Sends are performed in daemon threads to avoid blocking the application.
    """

    def emit(self, record: logging.LogRecord) -> None:
        """Forward the log record to the server."""
        # Prevent infinite recursion: skip logs generated by this module
        if record.name == __name__:
            return

        # Format the message and dispatch in a background thread
        try:
            message = self.format(record)
        except Exception:
            message = str(record.getMessage())

        thread = threading.Thread(
            target=send_log_to_server,
            args=(record.levelname, message),
            daemon=True,
        )
        thread.start()
